---                                                                                                                   
kind: Template                                                                                                        
apiVersion: template.openshift.io/v1                                                                                  
metadata:                                                                                                             
  name: nodejs-service                                                                                                
  annotations:                                                                                                        
    openshift.io/display-name: nodejs                                                                                 
    description: Example Service API for the Unified Hybrid Cloud deployment                                          
    tags: nodejs,uhc,service-delivery                                                                                 
    iconClass: icon-shadowman                                                                                         
    template.openshift.io/provider-display-name: Red Hat, Inc.                                                        
    template.openshift.io/documentation-url: https://gitlab.cee.redhat.com/service/                                   
labels:                                                                                                               
  template: nodejs-app                                                                                                
                                                                                                                      
objects:                                                                                                              
  - apiVersion: v1                                                                                                    
    kind: Service                                                                                                     
    metadata:                                                                                                         
      annotations:                                                                                                    
        kompose.service.group: nodejs-app                                                                             
        kompose.volume.type: configMap                                                                                
      creationTimestamp: null 
      labels:
        io.kompose.service: nodejs-app
      name: nodejs-app
    spec:
      ports:
        - name: "3001"
          port: 3001
          targetPort: 3001
      selector:
        io.kompose.service: trex
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.service.group: nodejs-app
        kompose.volume.type: configMap
      creationTimestamp: null
      labels:
        io.kompose.service: nodejs-app
      name: my-nodejs
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: nodejs-app
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.service.group: "nodejs-app"
            kompose.volume.type: "configMap"
          creationTimestamp: null
          labels:
            io.kompose.network/rh-trex-default: "true"
            io.kompose.service: nodejs-app
        spec:
          containers:
            - image: quay.io/redhat-user-workloads-stage/ysubrama-tenant/devfile-sample/my-component:build-3bd2e-1711628203
              name: my-nodejs
              ports:
                - containerPort: 3001
                  protocol: TCP
                  name: http
              resources: {}
          restartPolicy: Always
